import { EventItem } from "./types";

export const FEATURED_EVENTS: EventItem[] = [
  {
    id: "cyber-symphony-2026",
    title: "Cyber Symphony 2026 World Tour",
    subtitle: "Orchestral Electronic Live at Neon Horizon Arena",
    artist: "Daft Punk & London Philharmonic",
    venue: "Neon Horizon Amphitheater",
    city: "San Francisco, CA",
    date: "Saturday, Nov 14, 2026",
    time: "8:00 PM PST",
    category: "Concerts",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=800&auto=format&fit=crop",
    bannerImage: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=1600&auto=format&fit=crop",
    minPrice: 65,
    maxPrice: 250,
    vipPerks: ["Soundcheck Access", "Lounge Open Bar", "Front Gold Circle Seat", "Commemorative Hologram Pass"],
    totalSeats: 50,
    status: "ON_SALE"
  },
  {
    id: "eras-tour-san-francisco",
    title: "Taylor Swift — The Eras Tour (Final Encore)",
    subtitle: "The Record-Breaking Global Phenomenon",
    artist: "Taylor Swift",
    venue: "Levi's Stadium",
    city: "Santa Clara, CA",
    date: "Friday, Dec 04, 2026",
    time: "7:00 PM PST",
    category: "Concerts",
    image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?q=80&w=800&auto=format&fit=crop",
    bannerImage: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1600&auto=format&fit=crop",
    minPrice: 120,
    maxPrice: 450,
    vipPerks: ["VIP Merch Package", "Early Venue Entry", "Dedicated VIP Concierge"],
    totalSeats: 250,
    status: "ALMOST_FULL"
  },
  {
    id: "f1-las-vegas-gp",
    title: "Formula 1 Las Vegas Grand Prix 2026",
    subtitle: "Night Racing on the Las Vegas Strip",
    artist: "FIA Formula One World Championship",
    venue: "Las Vegas Strip Circuit",
    city: "Las Vegas, NV",
    date: "Sunday, Nov 22, 2026",
    time: "10:00 PM PST",
    category: "Sports",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=800&auto=format&fit=crop",
    bannerImage: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop",
    minPrice: 185,
    maxPrice: 650,
    vipPerks: ["Paddock Club Hospitality", "Pit Lane Walk", "Driver Q&A"],
    totalSeats: 100,
    status: "ON_SALE"
  },
  {
    id: "coachella-valley-2027",
    title: "Coachella Valley Music & Arts Festival",
    subtitle: "Weekend 1 Pass — Empire Polo Club",
    artist: "Multi-Headliner Lineup",
    venue: "Empire Polo Club",
    city: "Indio, CA",
    date: "April 16–18, 2027",
    time: "12:00 PM PDT",
    category: "Festivals",
    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?q=80&w=800&auto=format&fit=crop",
    bannerImage: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1600&auto=format&fit=crop",
    minPrice: 220,
    maxPrice: 599,
    vipPerks: ["Exclusive Air-Conditioned Lounges", "Main Stage VIP Viewing Area", "Shuttle Pass"],
    totalSeats: 500,
    status: "ON_SALE"
  }
];
